# Generated by Django 5.2.4 on 2025-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
